- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat/tasks/nginx.yml
- ansible/roles/sortinghat/tasks/virtualhost.yml
- ansible/roles/sortinghat/templates/vhost.j2
This commit allows SortingHat Nginx to enable SSL verification as optional.
Signed-off-by: Quan Zhou <quan@bitergia.com>
> [ansible] Allow SSL verification to SortingHat Nginx

- ansible/roles/mordred/defaults/main.yml
This commit updates the GrimoireLab version to 0.8.0.
Signed-off-by: Daniel Rodríguez <drodr@bitergia.com>
> [ansible] Upgrade GrimoireLab to 0.8.0

- docs/prerequisites.md
This commit fixes the `bap-deployment-toolkit` clone URL at `prerequisites.md`.
> [docs] Fix clone 'bap-deployment-toolkit' repository

- ansible/roles/mordred/tasks/configure_instance.yml
This commit fixes OpenSearch hostname in the Mordred role. Since
instances use prefixes in their names, `opensearch-0` is not
longer valid. Instead of that it uses the first hostname of the
`opensearch` group.
> [ansible] Fix OpenSearch hostname in Mordred role

- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch/tasks/snapshots.yml
- ansible/roles/opensearch/templates/make_snapshot.sh.j2
This commit removes the `gsutil resync` between buckets when the `restore_snapshot` is defined (it will take very long, maybe days if there are a lot of data). Instead of that it will restore the snapshot from the old bucket to the new OpenSearch instance.
> [ansible] Remove gsutil rsync bucket in restore opensearch role

- ansible/playbooks/nginx.yml
- ansible/playbooks/opensearch_dashboards.yml
- ansible/playbooks/sortinghat.yml
- ansible/roles/mordred/tasks/configure_instance.yml
- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/tasks/virtualhost.yml
- ansible/roles/nginx/templates/vhost.j2
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/opensearch_dashboards/tasks/main.yml
- ansible/roles/opensearch_dashboards/templates/opensearch_dashboards.yml.j2
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat/tasks/main.yml
- docs/deployment_and_config.md
- docs/provision.md
- terraform/modules/bap_env_gcp/opensearch_dashboard_anonymous.tf
- terraform/modules/bap_env_gcp/variables.tf
This commit creates a new terraform file in the `bap_env_gcp` module named `opensearch_dashboard_anonymous.tf` to create a machine for OpenSearch Dashboards with anonymous access.
Also, update the Ansible `opensearch_dashboards` role. Depending on whether the hostname belongs to the `opensearch_dashboards` inventory group, it will deploy OpenSearch Dashboards disabling the anonymous user, but if it belongs to the
`opensearch_dashboards_anonymous` inventory group, it will deploy OpenSearch Dashboards with the anonymous user.
> Support private and anonymous OpenSearch Dashboards

- ansible/roles/common/tasks/main.yml
- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/gcs.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/templates/vhost.j2
- terraform/modules/bap_env_gcp/storage.tf
- terraform/modules/bap_env_gcp/variables.tf
These commits change the way Nginx serves SortingHat static files,
using local files synced from GCS bucket instead of accesing
remotely. Public access to bucket is not longer available.
> Nginx serve SortingHat static files locally

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/mordred/tasks/configure.yml
- docs/deployment_and_config.md
This commit allows a custom SSH key pair by adding this section on the `main.yml`(defaults) or `vars.yml`(inventory).
```
mordred_ssh:
private: "<SSH_PRIVATE_PATH>"
public: "<SSH_PUBLIC_PATH>"
```
> [mordred] Allow custom SSH key pair

- ansible/roles/mordred/tasks/configure.yml
- ansible/roles/mordred/tasks/configure_instance.yml
- ansible/roles/mordred/tasks/main.yml
This commit creates the `grimoire` group and user including SSH key for machine `mordred` with the correct permissions.
> [mordred] Create grimore group and user with SSH key

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/mordred/files/create_roles_tenant.py
- ansible/roles/mordred/tasks/configure_instance.yml
- docs/deployment_and_config.md
This commit allows the option to overwrite roles and tenant of a project only if the `overwrite_roles` variable is set to `true` in `mordred_instances`.
```
mordred_instances:
- project: project1
tenant: project1
overwrite_roles: true
sources:
repository: "<PROJECT1_SOURCE_REPO_URL>"
```
> [mordred] Allows option to overwrite roles and tenant

- ansible/playbooks/monitoring.yml
- ansible/roles/monitoring/defaults/main.yml
- ansible/roles/monitoring/tasks/main.yml
- ansible/roles/monitoring/tasks/mariadb.yml
- ansible/roles/monitoring/tasks/nginx.yml
- ansible/roles/monitoring/tasks/redis.yml
- ansible/roles/monitoring/templates/docker_ops_agent.yaml.j2
- ansible/roles/monitoring/templates/mariadb_ops_agent.yaml.j2
- ansible/roles/monitoring/templates/nginx_ops_agent.yaml.j2
- ansible/roles/monitoring/templates/redis_ops_agent.yaml.j2
- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/tasks/virtualhost.yml
- ansible/roles/nginx/templates/status.conf.j2
- ansible/roles/redis/defaults/main.yml
- ansible/roles/redis/files/overrides.conf
- ansible/roles/redis/tasks/main.yml
This commit adds the monitoring role to customize ops_agent.yaml file for each VM if needed.
For now, there are four types of configurations:
- Docker logs: logging
- MariaDB: logging(docker logs) and metrics
- Redis: logging and metrics
- NGINX: logging and metrics
> [monitoring] Add monitoring role to customize config files

- ansible/roles/mordred/tasks/configure.yml
This commit ensures the SSH key pair has the correct permissions.
> [mordred] Set the correct permissions for the SSH key pair

- ansible/roles/mariadb/defaults/main.yml
- ansible/roles/mariadb/tasks/main.yml
This parameter allows to set the number of seconds a connection can be active in MariaDB. Useful to increase when there are for long processes in BAP such as unification or affiliation of individuals.
> [mariadb] Add wait_timeout parameter

- ansible/roles/mariadb/tasks/main.yml
- ansible/roles/mariadb/templates/mariadb_backup.sh.j2
- docs/deployment_and_config.md
This code creates a backup service account with the minimum required permissions to create backups. Also, it creates a backup for each database in MariaDB.
Fixes #46
> [mariadb] Create MariaDB backups per database

- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/virtualhost.yml
- ansible/roles/nginx/templates/opensearch_nodes.j2
- ansible/roles/nginx/templates/vhost.j2
- docs/deployment_and_config.md
This commit opens the OpenSearch endpoint at `/data`.
> [nginx] Open OpenSearch endpoint at "/data"

- ansible/roles/mariadb/defaults/main.yml
- ansible/roles/mariadb/tasks/main.yml
- docs/deployment_and_config.md
Add the `innodb_buffer_pool_size` parameter to improve the MariaDB performance in the docker command. A good value is 70%-80% of available memory.
> [mariadb] Improve performance using `innodb_buffer_pool_size`

- terraform/modules/bap_env_gcp/nginx.tf
- terraform/modules/bap_gcp_instance/main.tf
- terraform/modules/bap_gcp_instance/variables.tf
This commit adds `storage-ro` service account scope to Nginx to download the SortingHat static files from a Google Cloud Store Bucket.
> [terraform] Add "storage-ro" service account scope to Nginx VM

- ansible/roles/nginx/templates/vhost.j2
- ansible/roles/sortinghat/defaults/main.yml
- docs/deployment_and_config.md
- docs/prerequisites.md
- docs/provision.md
- terraform/modules/bap_env_gcp/network.tf
- terraform/modules/bap_env_gcp/nginx.tf
- terraform/modules/bap_env_gcp/variables.tf
Option to active GCP IAP tunnel by setting the `network_iap_tunnel = true` in the environment TF file.
Solves #51
> [terraform] Add GCP IAP tunnel

- ansible/roles/nginx/templates/vhost.j2
- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
This code replaces the `-` character with `_` because in MariaDB the `-` character is not valid for the database name.
> [sortinghat] Fix tenant name

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
This commit updates the version of BAP to 0.14.0 deployed with the toolkit.
> Bump BAP version to 0.14.0

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
This commit updates the version of BAP to 0.14.2 deployed with the toolkit.
> Bump BAP version to 0.14.2

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/mordred/tasks/configure.yml
- ansible/roles/mordred/tasks/configure_instance.yml
- ansible/roles/mordred/tasks/main.yml
- ansible/roles/mordred/templates/gitconfig.j2
- docs/deployment_and_config.md
This commit adds support for multiple Mordred hosts. This allows us to choose which host the Mordreds are deployed on.
> [mordred] Add support for multiple Mordred hosts

- ansible/roles/sortinghat/tasks/main.yml
This commit fixes the `Create databases` job when the SortingHat multi-tenant is disabled. This is only required when multi-tenant is enabled.
> [sortinghat] Fix 'Create databases' job

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
This commit updates the version of BAP to 0.15.0 deployed with the toolkit.
> Bump BAP version to 0.15.0

- ansible/roles/nginx/templates/vhost.j2
The error is `nignx` instead of `nginx`.
> [nginx] Fix typo in vhost.j2 template

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
This commit updates the version of BAP to 0.16.0 deployed with the toolkit.
> Bump BAP version to 0.16.0

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
This commit updates the version of BAP to 0.16.2 deployed with the toolkit.
> Bump BAP version to 0.16.2

- ansible/roles/mordred/files/create_roles_tenant.py
- ansible/roles/mordred/tasks/configure_instance.yml
This commit adds two new roles:
- `bap_<tenant>_pseudonymize_role`: pseudonymize author fields
- `bap_plugins_visibility`: Hide OpenSearch Dashboards plugins
> [mordred] Add pseudonymize and plugins visibility roles

- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/templates/vhost.j2
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
- docs/deployment_and_config.md
For BAP 0.19.0/GrimoireLab 0.22.0, the support for dedicated queues on SortingHat was added. Now on,
tenants can used dedicated queues to improve the
performance and security of identities jobs.
This commit adds that support, allowing the creation of dedicated workers for the tenants that require
this configuration. With this change, there will be two types of workers: normal workers, that will get the jobs from the 'default' queue; dedicated workers, one worker for each tenant that will only get jobs from queue with the same tenant name.
Some changes were also required on the ansible config. There's a new entry names 'sortinghat' under the instances var. This entry will store all the specific configuration related to each SortingHat instance. For example, OpenInfra tokens will be now …
> [sortinghat] Add dedicated workers/queues

- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
- docs/deployment_and_config.md
Remove duplicates entries on tenants configuration so there's only one entry when the same tenant config is assigned to multiple instances.
> [sortinghat] Check tenants config to remove duplicates

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
Updates the default variables to deploy BAP 0.19.1 docker images.
> Bump BAP version to 0.19.1 release

- ansible/roles/sortinghat/defaults/main.yml
This commit add all mordred hosts to `sortinghat_allowed_hosts` and `sortinghat_cors_allowed_origin` instead of just the first one.
> [sortinghat] Add all mordred hosts to sortinghat

- docs/provision.md
- terraform/modules/bap_env_gcp/mariadb.tf
- terraform/modules/bap_env_gcp/mordred.tf
- terraform/modules/bap_env_gcp/nginx.tf
- terraform/modules/bap_env_gcp/opensearch.tf
- terraform/modules/bap_env_gcp/opensearch_dashboard.tf
- terraform/modules/bap_env_gcp/opensearch_dashboard_anonymous.tf
- terraform/modules/bap_env_gcp/redis.tf
- terraform/modules/bap_env_gcp/sortinghat.tf
- terraform/modules/bap_env_gcp/sortinghat_worker.tf
- terraform/modules/bap_env_gcp/variables.tf
- terraform/modules/bap_gcp_instance/main.tf
- terraform/modules/bap_gcp_instance/outputs.tf
- terraform/modules/bap_gcp_instance/variables.tf
This commit adds an option to create persistent disks and attach them to instances (VM).
All default boot disk size values are changed to 10 (minimum).
If the disk count is 0 or not set it will use the node count. which means the number of the
disks are the same as the number of node counts for that type of VM and it will attach to
those VMs.
Add these configurations on the `environments.tf` file
```
mariadb_disk_count = 1
mariadb_disk_attach = "<YOUR-MARIADB-INSTANCE-NAME>"
disk_redis_snapshot = "<SNAPSHOT-DISK-NAME>"
```
> [terraform] Add GCP persistent disk

- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat/templates/vhost.j2
- docs/deployment_and_config.md
The `max_conns` limits the maximum number of simultaneous active connections to the proxied server to avoid the `upstream timed out` error (uWSGI is limited to 100 simultaneous connections).
> [sortinghat] Add "max_conns" parameter at Nginx

- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
This commit updates the SORTINGHAT_CONFIG env variable to use the new settings (`sortinghat.config.settings_bap`) available in the SortingHat images for BAP.
> Update the SortingHat configuration to use BAP settings

- terraform/modules/bap_alerting_gcp/variables.tf
- terraform/modules/bap_alerting_gcp/virtual_machine.tf
This change improves alerts to be more useful:
New alert:
- `VM Instance - High CPU Utilization (1h)`
- threshold: 75.0%
- rolling window: 1h
Changes:
- `VM Instance - High CPU Utilization (10min)`
- from: 5min rolling window
- to: 10min rolling window
- `VM Instance - High Disk Utilization`
- from: 95% threshold
- to: 80% threshold
> [terraform] Improve alerts

- terraform/modules/bap_alerting_gcp/virtual_machine.tf
The documentation of `VM Instance - High CPU Utilization (10min)` alert is now updated accordingly to the configuration (rolling window 10min).
> [terraform] Fix High CPU (10min) documentation

- ansible/playbooks/all_in_one.yml
- ansible/roles/mariadb/defaults/main.yml
- ansible/roles/mariadb/tasks/main.yml
- ansible/roles/mariadb/tasks/test.yml
- ansible/roles/mariadb/templates/mariadb_backup.sh.j2
- ansible/roles/mordred/defaults/main.yml
- ansible/roles/mordred/tasks/configure_instance.yml
- ansible/roles/mordred/tasks/main.yml
- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/templates/opensearch_nodes.j2
- ansible/roles/nginx/templates/status.conf.j2
- ansible/roles/nginx/templates/vhost.j2
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch/tasks/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/opensearch_dashboards/tasks/main.yml
- ansible/roles/redis/defaults/main.yml
- ansible/roles/redis/tasks/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat/tasks/nginx.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
- docs/architecture_overview.md
- docs/deployment_and_config.md
- docs/provision.md
- terraform/modules/bap_env_gcp/all_in_one.tf
- terraform/modules/bap_env_gcp/variables.tf
We have one VM for each BAP service:
- MariaDB
- Redis
- OpenSearch
- OpenSearch Dashboards
- SortingHat
- SortingHat Workers
- Nginx
- Mordred
The goal is to provide the option to deploy all BAP services in a single VM.
>  Allow deployment of all BAP services in a single VM

- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch/tasks/security_admin.yml
- ansible/roles/opensearch/templates/opensearch.yml.j2
This commit configures the Audit Log with the following parameters:
- Category: `AUTHENTICATED`
- Ignored users: kibanaserver and Mordred users
- Ignored requests:
- /_mget*
- /_plugins*
- /_template
- /_search
- /_mapping*
- /_cat*
- /_alias*
- /_cluster*
- /.kibana/_search
- /.kibana/_doc/config*
- /_resolve*
> [opensearch] Add Audit Log configuration

- ansible/roles/sortinghat/tasks/main.yml
This commit fixes the regex to include numbers and `_` in `sortinghat_cors_allowed_origins_regexes`.
> [sortinghat] Fix subdomain regex

- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/certbot.yml
- ansible/roles/nginx/templates/certbot_renew.sh.j2
This code creates new certificates if they do not exist and the
crontab script checks daily if the certificates are still valid
and renew them if necessary. By default, if the expiration time
is less than 30 days, it will be renewed (it can be changed by
setting the `nginx_letsencrypt_cert_warning_days` parameter).
> [nginx] Improve certbot renew tasks

- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/opensearch_dashboards/templates/opensearch_dashboards.yml.j2
- docs/deployment_and_config.md
This commit fixes OpenID configuration int the OpenSearch Dashboards template and supports multiple authorization (Basic authorization and OpenID).
Fixes #93
> [OpenID] Fix template and support multiple authorization

- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch/tasks/main.yml
- ansible/roles/opensearch/tasks/restore_security_backup.yml
- ansible/roles/opensearch/tasks/security_backup.yml
- ansible/roles/opensearch/tasks/security_config.yml
- ansible/roles/opensearch/tasks/snapshots.yml
- ansible/roles/opensearch/templates/boto.j2
- ansible/roles/opensearch/templates/opensearch-security/backup.sh.j2
- docs/deployment_and_config.md
This commit creates OpenSearch Security daily backup and uploads them to a GCP bucket, it also allows the restoration of these files configurating `opensearch_security_backup_restore` and `opensearch_security_backup_restore_name` parameters.
> [opensearch] Create OpenSearch Security backup

- ansible/roles/sortinghat_worker/tasks/main.yml
This commit fixes the host at create MariaDB service account task. The `ansible_all_ipv4_addresses` value is a list of all addressess instead of the main IP (`ansible_default_ipv4.address`).
> [sortinghat_worker] Fix host (ansible_default_ipv4.address)

- ansible/roles/opensearch/templates/opensearch-security/backup.sh.j2
This commit removes the MIME type header from the OpenSearch security compressed backup (tgz) file in the upload process to the GCP bucket.
> [opensearch] Remove MIME type header in the security backup

- ansible/roles/mordred/defaults/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
It updates docker images to run BAP 0.26.0.
> Bump BAP version to 0.26.0

- ansible/roles/mariadb/defaults/main.yml
- ansible/roles/mariadb/tasks/main.yml
- ansible/roles/mordred/defaults/main.yml
- ansible/roles/mordred/tasks/main.yml
- ansible/roles/nginx/defaults/main.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/opensearch/defaults/main.yml
- ansible/roles/opensearch/tasks/main.yml
- ansible/roles/opensearch_dashboards/defaults/main.yml
- ansible/roles/opensearch_dashboards/tasks/main.yml
- ansible/roles/redis/defaults/main.yml
- ansible/roles/redis/tasks/main.yml
- ansible/roles/sortinghat/defaults/main.yml
- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat/tasks/nginx.yml
- ansible/roles/sortinghat_worker/defaults/main.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
This commit adds a docker container log size limit (stored at `/var/lib/docker/containers/<container-ID>/<container-ID>-json.log`) to prevent the disk from filling up.
> [docker] Add max-size log options to all docker containers

- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/tasks/virtualhost.yml
All instance configurations require an `nginx.fqdn`, but with this change, it is optional. Thus, it is possible to deploy a Mordred without a virtual host.
> [nginx] Allow deploying Mordred without a virtual host

- ansible/roles/nginx/templates/vhost.j2
Mozilla uses this list, and it avoids two weak algorithms
- ECDHE-ECDSA-AES256-SHA384 (TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA)
- ECDHE-ECDSA-AES256-GCM-SHA384 (TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384)
https://wiki.mozilla.org/Security/Server_Side_TLS
> [nginx] Update ssl_ciphers list

- ansible/roles/mordred/defaults/main.yml
OpenSearch cluster has two types (manager and data) and configure 'opensearch_host' as manager node.
> [mordred] Fix opensearch_host

- ansible/roles/nginx/templates/vhost.j2
Disables emitting nginx version on error pages and in the “Server” response header field.
> [nginx] Disable version

- ansible/roles/mariadb/tasks/main.yml
- ansible/roles/mordred/tasks/main.yml
- ansible/roles/nginx/tasks/gcs.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/tasks/virtualhost.yml
- ansible/roles/nginx/tasks/virtualhost_default.yml
- ansible/roles/opensearch/tasks/certificates.yml
- ansible/roles/opensearch/tasks/security_config.yml
- ansible/roles/opensearch/tasks/snapshots.yml
- ansible/roles/sortinghat/tasks/main.yml
- ansible/roles/sortinghat/tasks/virtualhost.yml
- ansible/roles/sortinghat_worker/tasks/main.yml
This commit disables logging of tasks with any secrets by adding `no_log: true` to that task.
> [ansible] Disable logging for tasks with a secret

- ansible/roles/monitoring/defaults/main.yml
- ansible/roles/monitoring/templates/nginx_ops_agent.yaml.j2
- ansible/roles/nginx/files/logrotate.conf
- ansible/roles/nginx/tasks/certbot.yml
- ansible/roles/nginx/tasks/main.yml
- ansible/roles/nginx/templates/certbot_renew.sh.j2
- ansible/roles/nginx/templates/nginx_logrotate.j2
- terraform/modules/bap_alerting_gcp/nginx.tf
Create a new metric and alert for Nginx to check if Certbot successfully renewed the certificates.
Improves the `certbot_renew.sh` script and the output to make it more suitable for GCP Logging to consume. The Nginx container will only restart once all certificates have been checked and if any have been renewed. Also, add logrotate to the logs:
- `{{ nginx_log_dir }}/*.log`
- `{{ nginx_letsencrypt_logsdir }}/*.log`
Fixes #132
> Nginx certbot alert
