README.md

Add a link to Ángel profile for better recognition

Improve Ángel acknowledgement

---

ansible/roles/sortinghat_worker/defaults/main.yml
ansible/roles/sortinghat_worker/tasks/main.yml
docs/deployment_and_config.md

This commit allows to deploy multiple SortingHat Worker containers in the same machine.

[sortinghat_worker] Allow deploy multiple containers

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/mordred/tasks/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This image replaces GrimoireLab. The Bitergia Analytics image is based on GrimoireLab but contains specific software developed by Bitergia and adapted to their customers.

Deploy platform with Bitergia Analytics image

---

ansible/roles/sortinghat_worker/defaults/main.yml
ansible/roles/sortinghat_worker/tasks/main.yml
docs/deployment_and_config.md

This commit defines the client_id and client_secret of OpenInfra.

[sortinghat-worker] Add OpenInfra

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This commit updates the version of BAP images to 0.7.0

Deploy BAP 0.7.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

With this change, the code will deploy BAP 0.7.1.

Update BAP to 0.7.1

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

With this change, the code will deploy BAP 0.7.2.

Update BAP to 0.7.2

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

The toolkit will deploy BAP 0.8.0.

Update BAP to 0.8.0

---

ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat/tasks/main.yml
docs/deployment_and_config.md

This commit allows customization of uWSGI workers and threads:
- `sortinghat_uwsgi_workers`: number of workers
- `sortinghat_uwsgi_threads`: number of threars

[sortinghat] Add uWSGI workers and threads

---

ansible/roles/mordred/files/logrotate.conf
ansible/roles/mordred/tasks/configure.yml
ansible/roles/mordred/templates/mordred_logrotate.j2

This commit adds logrotate for all Mordred logs.

[mordred] Add logrotate

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

The toolkit will deploy BAP 0.9.0.

Update BAP to 0.9.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This version of the toolkit deploys BAP 0.10.0.

Update BAP to 0.10.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This version of the toolkit deploys BAP 0.11.0.

Update BAP to 0.11.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This version of the toolkit deploys BAP 0.12.0.

Update BAP to 0.12.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This version of the toolkit deploys BAP 0.13.0.

Update BAP to 0.13.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

It updates docker images to run BAP 0.19.0.

Bump BAP version to 0.19.0

---

ansible/roles/sortinghat/tasks/main.yml
ansible/roles/sortinghat_worker/tasks/main.yml

There was a typo in this variable, so the worker set the value as empty.

[sortinghat] Fix openinfra_client_id var name

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

This version fixes some problems with SortingHat and with kitsune backend.

Bump BAP version to 0.19.2

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Update docker images to run BAP 0.20.1

Bump BAP version to 0.20.1

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Update docker images to run BAP 0.21.0

Bump BAP version to 0.21.0

---

ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat/tasks/main.yml

This commits update `sortinghat_allowed_hosts` to use domains and `sortinghat_cors_allowed_origins_regexes` to use regular expression

[sortinghat] Update allowed hosts/cors using domains and regexes

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Update Docker images to run BAP 0.22.0

Bump BAP version to 0.22.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Update Docker images to run BAP 0.22.2

Bump BAP version to 0.22.2

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Update Docker images to run BAP 0.22.3

Bump BAP version to 0.22.3

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Update Docker images to run BAP 0.23.0

Bump BAP version to 0.23.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

It updates docker images to run BAP 0.24.0.

Bump BAP version to 0.24.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

It updates docker images to run BAP 0.25.0.

Bump BAP version to 0.25.0

---

ansible/playbooks/monitoring.yml
ansible/roles/monitoring/defaults/main.yml
ansible/roles/monitoring/tasks/opensearch.yml
ansible/roles/monitoring/templates/opensearch_ops_agent.yaml.j2
terraform/modules/bap_alerting_gcp/opensearch.tf

This commit adds OpenSearch server metric and absent alert.

[alerts] Add OpenSearch metric and alert

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

It updates docker images to run BAP 0.25.1.

Bump BAP version to 0.25.1

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/opensearch_dashboards/templates/opensearch_dashboards.yml.j2

Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.

Migrate files for branch rename from master to main

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

It updates docker images to run BAP 0.27.0.

Bump BAP version to 0.27.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Bump BAP version to 0.28.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Bump BAP version to 0.29.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Bump BAP version to 0.31.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Bump BAP version to 0.32.0

---

ansible/roles/mordred/defaults/main.yml
ansible/roles/opensearch/defaults/main.yml
ansible/roles/opensearch_dashboards/defaults/main.yml
ansible/roles/sortinghat/defaults/main.yml
ansible/roles/sortinghat_worker/defaults/main.yml

Bump BAP version to 0.32.1

---

ansible/roles/redis/defaults/main.yml
ansible/roles/redis/files/overrides.conf
ansible/roles/redis/tasks/main.yml

Change Redis settings to use the Valkey Docker image.
This includes updating the log file path and environment variables to ensure compatibility with the new image.

update Redis configuration for Valkey image
